### ISSUE TITLE
Catch2 will not build with GCC8.3 on MacOS Mojave

### ISSUE THREAD

**Issue by madmongo1** [catchorg/Catch2#1591]
**Describe the bug**

Using a toolchain which targets the homebrew gcc8.3 on MacOS causes the following failure when building the Catch2 project:

```
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/sysctl.h:83,
                 from /Users/richardhodges/github/QuoineFinancial/Catch2-1/include/internal/catch_debugger.cpp:21:
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/ucred.h:94:2: error: '_Atomic' does not name a type
  _Atomic u_long          cr_ref;  /* reference count */
  ^~~~~~~
```

**Expected behavior**

A successful compile

**Reproduction steps**

```
$ mkdir build
$ cd build
$ cmake -DCMAKE_TOOLCHAIN_FILE=${HOME}/github/ruslo/polly/gcc-8-cxx17.cmake ..
$ make
```

The toolchain file can be located here: https://github.com/ruslo/polly/blob/master/gcc-8-cxx17.cmake

**Platform information:**
 - OS: MacOS Mojave 10.14.4
 - Compiler+version: GCC 8.3 (homebrew)
 - Catch version: 2.7.0 and 2.5.0 both exhibit the problem

**Additional context**

The problem is in catch_debugger.cpp. Because the system is detected as MacOS, the following code is compiled...

```
#ifdef CATCH_PLATFORM_MAC

#  include <assert.h>
#  include <stdbool.h>
#  include <sys/types.h>
#  include <unistd.h>
#  include <sys/sysctl.h>
#  include <cstddef>
#  include <ostream>
```

`sysctl.h` is including `ucred.h`, which references the nonstandard (in c++) `_Atomic` keyword which gcc does not support (and clang does).

I'm not sure where to go from here. GCC has marked this issue as WONTFIX as they claim there is no need to support nonstandard keywords in gcc.

This issue did not occur on previous versions of MacOS. It seems that someone at Apple has allowed the nonstandard `_Atomic` keyword to leak into system header interfaces.

Current workaround is to use a linux computer for running compatibility-check compiles on gcc.

**Comment by horenmar** [comment]
Thanks (and 👍) for the detailed report, but it has already been reported as #1588. Right now the fix (#1589) is waiting to see if this actually reproduces with non-apple Clang as well, or if it needs to be done only for GCC.

**Comment by madmongo1** [comment]
@horenmar good to know, thanks.

**Comment by madmongo1** [comment]
Possibly relevant:
https://stackoverflow.com/q/45342776/2015579

**Comment by horenmar** [comment]
Can you test the build with Clang from homebrew?

**Comment by madmongo1** [comment]
Will need to compile it but theoretically, yes. I'm in an airport right
now. Will test within 24 hrs

**Comment by horenmar** [comment]
The fix is merged to master.

**Comment by sureshjoshi** [comment]
Just a note, for what it's worth after the fact - I'm using Catch 2.7.0, and the Brew-installed clang and have never run into this issue.

While testing some cross-platform compatibility, I got hit by this bug when using gcc 8.2 (which led me to https://apple.stackexchange.com/questions/355049/compilation-error-with-mojave-error-atomic-does-not-name-a-type and somehow that led me here eventually).

I'll update to the merged Catch and report back with my findings.

**Comment by sureshjoshi** [comment]
Annnnd success! Using the master branch today and generating a drop-in replacement single file header to my project allows me to compile in Homebrew's clang (10.0.1) or gcc (8.3.0)

**Comment by kartikkumar** [comment]
With gcc 8.3.0 installed through Homebrew, and with the latest code on master, I'm still hitting this issue. 

Any suggestions on how to resolve this without having to manually patch and recompile gcc, as suggested on StackExchange?

My understanding is that this was resolved with the fix that was merged on master, so curious if others are still having trouble too.

**Comment by horenmar** [comment]
@kartikkumar Did you regenerate the single header file?

**Comment by kartikkumar** [comment]
@horenmar I only fetched and rebased the master branch. I had a look at the thread on StackExchange, which seems to suggest patching and rebuilding GCC itself. I haven't seen anything about regenerating the single header file itself. How do I got about doing that? (apologies if this has been answered elsewhere already).

**Comment by sureshjoshi** [comment]
@kartikkumar It looks like Catch 2.7.2 was released which should have this fix applied.

In any case, what I did when I pulled down the latest master branch was to then run `scripts/generateSingleHeader.py` to create a single file header I could use as a drop-in replacement.

**Comment by kartikkumar** [comment]
@sureshjoshi that did it, thanks a lot! Never looks in the `scripts` dir :)
