### ISSUE TITLE
Build error with noexcept and VS2013

### ISSUE THREAD

**Issue by philippeVerney** [catchorg/Catch2#1123]
Hello

## Description
I just received a PR to upgrade from catch v1.5.6 to v2.0.1 in my library.
However, my automatic build with appVeyor fails using v2.0.1.
Appveyor build is on VS2013. the PR was tested on VS2015.

### Steps to reproduce
upgrade to v2.0.1
try to build with VS2013

### Extra information
Here is the first error message :  "catch.hpp(353): error C3646: 'noexcept' : unknown override specifier"
The full log is here : https://ci.appveyor.com/project/philippeVerney/fesapi/build/1.0.29 starting at line 31789

I think noexcept is not supported by VS2013 : https://stackoverflow.com/questions/18387640/how-to-deal-with-noexcept-in-visual-studio

Maybe catch2 is not aimed to support VS2013. This page looks unmaintained : https://github.com/catchorg/Catch2/wiki/What-compilers-does-CATCH-work-with

**Comment by philsquared** [comment]
You are correct that VS2013 is not supported by Catch2 (as it's C++11 support is not sufficient).
You are also correct that that wiki page is not maintained - in fact the entire wiki was deleted at least four years ago! I'm impressed you managed to find (or have held onto) that URL - and that it still works!

AFAICS we don't have an equivalent page in the current docs, although https://github.com/catchorg/Catch2/blob/master/docs/limitations.md is close (and also needs updating in places).

You can also look at our Travis and AppVeyor builds:

https://travis-ci.org/catchorg/Catch2
https://ci.appveyor.com/project/catchorg/catch2

As you can see, on Windows, we're only testing on VS 2015 and VS 2017.

Sorry if it's not what you wanted to hear. Your options seem to be either (a) drop support for VS2013 or (b) stay on Catch 1.x.

**Comment by philippeVerney** [comment]
Thanks for your quick answer. It confirms what I thought.
I am going to stay with Catch 1.x for a while (I still have VS2013 support in mind). My main goal to upgrade to Catch2 was to avoid some Codacy warnings but Catch2 also have Codacy warnings. I'll just ignore catch.hpp with codacy.

Thanks again!

**Comment by philsquared** [comment]
What are the Codacy warnings?

**Comment by philippeVerney** [comment]
I think this Codacy report page is public and then you should look at it : https://www.codacy.com/app/F2I-Consulting/fesapi/pullRequest?prid=1132125

Just to be clear, I don't have a need for these warnings to be resolved. It was just "nicer" imho to not have warnings on the report. Furthermore, I can ignore a file presumably in Codacy.

**Comment by philippeVerney** [comment]
I close this issue since Codacy warning is irrelevant in this topic and probably also in a bigger scope. I did not enough look at Codacy report to judge if it is worse to study the warnings or not.

Thanks again for the quick and clear answer about my issue! I appreciate.

**Comment by philsquared** [comment]
Thanks.
Ah yes I know about most of those. Some are fair enough and I've been getting through them. Some I disagree with (e.g. it's actually better to pass `StringRef` by value).
In any case other harmful - but I'm not sure how to silence the ones that are "as designed" in Codacy.
