### ISSUE TITLE
error: invalid operands to binary expression

### ISSUE THREAD

**Issue by ryandesign** [catchorg/Catch2#1935]
**Describe the bug**
[catch2 2.12.1 does not build on OS X 10.9](https://build.macports.org/builders/ports-10.9_x86_64-builder/builds/119793/steps/install-port/logs/stdio). The first error is:

```
/path/to/catch2-2.12.1/projects/SelfTest/UsageTests/Approx.tests.cpp:197:14: error: invalid operands to binary expression ('<anonymous>::ApproxTests::StrongDoubleTypedef' and 'Catch::Detail::Approx')
  REQUIRE(td == Approx(10.0));
          ~~ ^  ~~~~~~~~~~~~
/path/to/catch2-2.12.1/include/catch.hpp:206:90: note: expanded from macro 'REQUIRE'
#define REQUIRE( ... ) INTERNAL_CATCH_TEST( "REQUIRE", Catch::ResultDisposition::Normal, __VA_ARGS__  )
                                                                                         ^
/path/to/catch2-2.12.1/include/internal/catch_capture.hpp:45:40: note: expanded from macro 'INTERNAL_CATCH_TEST'
        CATCH_INTERNAL_IGNORE_BUT_WARN(__VA_ARGS__); \
                                       ^
/path/to/catch2-2.12.1/include/internal/catch_compiler_capabilities.h:73:76: note: expanded from macro 'CATCH_INTERNAL_IGNORE_BUT_WARN'
#    define CATCH_INTERNAL_IGNORE_BUT_WARN(...) (void)__builtin_constant_p(__VA_ARGS__) /* NOLINT(cppcoreguidelines-pro-type-vararg) */
                                                                           ^
/path/to/catch2-2.12.1/include/internal/catch_approx.h:49:66: note: candidate template ignored: disabled by 'enable_if' [with T = <anonymous>::ApproxTests::StrongDoubleTypedef]
        template <typename T, typename = typename std::enable_if<std::is_constructible<double, T>::value>::type>
                                                                 ^
/path/to/catch2-2.12.1/include/internal/catch_approx.h:55:66: note: candidate template ignored: disabled by 'enable_if' [with T = Catch::Detail::Approx]
        template <typename T, typename = typename std::enable_if<std::is_constructible<double, T>::value>::type>
                                                                 ^
```

**Expected behavior**
Successful build

**Reproduction steps**
On OS X 10.9, [install MacPorts](https://www.macports.org/install.php) and [Xcode 6.2](https://developer.apple.com/download/more/?=Xcode%206.2) and run `sudo port install catch2` or compile it manually.

**Platform information:**

 - OS: OS X 10.9
 - Compiler+version: Apple LLVM version 6.0 (clang-600.0.57) (based on LLVM 3.5svn)
 - Catch version: 2.12.1

**Additional context**
This was previously reported in #946 but it was closed without being fixed.

**Comment by horenmar** [comment]
I don't have a Mac to reproduce this locally, and it seems to only target old platform.

If someone else finds a reasonable workaround I'll merge it, but I am not working on this on my own.

**Comment by ryandesign** [comment]
It [builds fine on Mac OS X 10.6](https://build.macports.org/builders/ports-10.6_x86_64-builder/builds/27095/steps/install-port/logs/stdio) when using libc++ (which is not the default for OS X 10.8 and earlier but is the default for OS X 10.9 and later) and the much newer clang 9.0.1 compiler as installed by MacPorts. So maybe it's just that Apple LLVM/clang 6.0 (the newest clang available from Apple on 10.9) is too old to compile this code.

Apple LLVM/clang 6.0 should support C++11 and the description of this GitHub repository says that catch2 is "using C++11, C++14, C++17 and later". Is it possible that this is no longer true? Is it possible that you are now using newer language features that are not part of C++11? I know very little C++, but for example I noticed that although `std::enable_if` was introduced in C++11, its [helper types](https://en.cppreference.com/w/cpp/types/enable_if) weren't introduced until C++14.

**Comment by horenmar** [comment]
As seen in the compilation message, Approx uses `std::enable_if<>::type`, which is the C++11 construct.  Anyway, if updating compiler/stdlib fixes this, it sounds like the problem is caused by the old libstdc++'s implementation of `is_constructible`. Going through the old issue, the problem there was that `is_constructible` does not handle explicitly convertible types properly. Just as with that issue, you can use Catch2 normally with that setup, as long as you don't need to use `Approx` together with types that are explicitly convertible to `double`.

**Comment by ryandesign** [comment]
> if updating compiler/stdlib fixes this, it sounds like the problem is caused by the old libstdc++'s implementation of `is_constructible`.

You mean libc++? libstdc++ is not being used here.

I've just tested on Mac OS X 10.7, which is the oldest version of macOS that includes a copy of libc++. So this is the oldest libc++ we should have to deal with. Catch2 builds fine there when using MacPorts clang 9.0.1. So the old libc++ isn't the problem; the old compiler is.

It has been my experience that Apple LLVM version 6.0 (clang-600.0.57) (and version 5.0 / 500 before it) is fully capable of compiling C++11 software, though it's certainly possible it had bugs and maybe this is one of those cases. Unfortunately I'm not able to make sense of the error messages due to my very limited C++ experience and complete lack of familiarity with the Catch2 source code.

> you can use Catch2 normally with that setup

Are you thinking of a different solution other than building with a newer compiler? Because using the older compiler it does not build so I'm not sure how I "can use Catch2 normally with that setup".

> as long as you don't need to use `Approx` together with types that are explicitly convertible to `double`.

I don't personally need to use anything. I'm not even familiar enough with Catch2 to know what it does. I'm just a developer with the MacPorts project, interested in making sure that the ports we offer build on as many OS versions as possible. 😄 So lacking any other ideas, I'll configure our builds to blacklist Apple clang < 700.
