### ISSUE TITLE
Advance warning during compilation with GCC 6.3.0

### ISSUE THREAD

**Issue by wimrijnders** [catchorg/Catch2#1323]
## Description

This is not a compilation error, but `GCC 6.3.0` is throwing a warning during compilation of `CATCH2 v.2.2.3`. I scanned the issues here and didn't find anything similar, so I'm reporting it.

I think it would be prudent to anticipate this before it becomes a problem.

### Steps to reproduce

- Take a program with unit tests, including "catch.hpp"
- Compile with `GCC 6.3.0`
- During compilation, the following warnings crop up:

```
In file included from /usr/include/c++/6/vector:64:0,
                 from Tests/catch.hpp:346,
                 from Tests/testMain.cpp:12:
/usr/include/c++/6/bits/stl_vector.h: In member function ‘std::vector<_Tp, _Alloc>::reverse_iterator std::vector<_Tp, _Alloc>::rbegin() [with _Tp = Catch::SectionEndInfo; _Alloc = std::allocator<Catch::SectionEndInfo>]’:
/usr/include/c++/6/bits/stl_vector.h:585:38: note: parameter passing for argument of type ‘__gnu_cxx::__normal_iterator<Catch::SectionEndInfo*, std::vector<Catch::SectionEndInfo> >’ will change in GCC 7.1
       { return reverse_iterator(end()); }

...etc. more like these follow
```

### Extra information

* Catch version: **CATCH2 v2.2.3**
* Operating System: Debian stretch on Raspberry Pi, uname: **Linux pascale 4.14.44+ #1117 Thu May 31 16:35:07 BST 2018 armv6l GNU/Linux**
* Compiler+version: **GCC v 6.3.0**

**Comment by horenmar** [comment]
That looks like you are using `-Wpsabi`. Since Catch does not, in any way, provide ABI guarantees, the ABI changes between GCC versions are not relevant to us.

**Comment by wimrijnders** [comment]
Let me check that...

**Comment by horenmar** [comment]
What the warning means is that if you compiled parts of your application using GCC 6.x and other parts using GCC 7.x, then either these parts will fail to link together (the better option), or the resulting binary will fail horribly during runtime (the more likely option).

This is relevant and important if you are linking against precompiled libraries, but Catch does not provide these and assumes that you will always build it with your current compiler, as we do not guarantee any sort of ABI stability -- even patch releases can (and often will) change Catch's ABI (as opposed to API, which we guarantee to be as stable as we can make it.)

**Comment by wimrijnders** [comment]
OK, that's interesting to know. So, as long as you don't mix different compiled versions you're safe. It also means that the project where the warning occurred is safe, but I can imagine other projects running into issues.

Thanks for the info! TIL.
