### ISSUE TITLE
Link fails due to missing Catch::LeakDetector::LeakDetector symbol in minimal CMake project on macOS

### ISSUE THREAD

**Issue by rcook** [catchorg/Catch2#1085]
## Description

Using a standard build of CMake and Clang on macOS, an executable including `catch.hpp` and defining the `CATCH_CONFIG_MAIN` macro compiles but fails to link due to missing symbols when using Catch2. This used to work using Catch1.x which I have confirmed by using the `Catch1.x` branch.

### Steps to reproduce

This is running on a MacBook Pro i7 running Mac OS X 10.10.5:

```
$ clang++ --version
Apple LLVM version 7.0.2 (clang-700.1.81)
Target: x86_64-apple-darwin14.5.0
Thread model: posix
$ cmake --version
cmake version 3.7.2

CMake suite maintained and supported by Kitware (kitware.com/cmake).


$ git clone https://github.com/catchorg/Catch2.git
Cloning into 'Catch2'...
$ cat << EOF > main.cpp
> #define CATCH_CONFIG_MAIN
> #include <catch.hpp>
> EOF
$ cat << EOF > CMakeLists.txt
> project(testexe)
> set(CMAKE_CXX_STANDARD 14)
> add_executable(testexe main.cpp)
> target_include_directories(testexe PUBLIC Catch2/include)
> EOF
$ mkdir build
$ cd build
$ cmake -G 'Unix Makefiles' ..
$ make VERBOSE=1
/usr/local/Cellar/cmake/3.7.2/bin/cmake -H/Users/someuser/src/REPRO -B/Users/someuser/src/REPRO/build --check-build-system CMakeFiles/Makefile.cmake 0
/usr/local/Cellar/cmake/3.7.2/bin/cmake -E cmake_progress_start /Users/someuser/src/REPRO/build/CMakeFiles /Users/someuser/src/REPRO/build/CMakeFiles/progress.marks
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f CMakeFiles/Makefile2 all
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f CMakeFiles/testexe.dir/build.make CMakeFiles/testexe.dir/depend
cd /Users/someuser/src/REPRO/build && /usr/local/Cellar/cmake/3.7.2/bin/cmake -E cmake_depends "Unix Makefiles" /Users/someuser/src/REPRO /Users/someuser/src/REPRO /Users/someuser/src/REPRO/build /Users/someuser/src/REPRO/build /Users/someuser/src/REPRO/build/CMakeFiles/testexe.dir/DependInfo.cmake --color=
Dependee "/Users/someuser/src/REPRO/build/CMakeFiles/testexe.dir/DependInfo.cmake" is newer than depender "/Users/someuser/src/REPRO/build/CMakeFiles/testexe.dir/depend.internal".
Dependee "/Users/someuser/src/REPRO/build/CMakeFiles/CMakeDirectoryInformation.cmake" is newer than depender "/Users/someuser/src/REPRO/build/CMakeFiles/testexe.dir/depend.internal".
[35m[1mScanning dependencies of target testexe[0m
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f CMakeFiles/testexe.dir/build.make CMakeFiles/testexe.dir/build
[ 50%] [32mBuilding CXX object CMakeFiles/testexe.dir/main.o[0m
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++    -I/Users/someuser/src/REPRO/Catch2/include  -std=gnu++14 -o CMakeFiles/testexe.dir/main.o -c /Users/someuser/src/REPRO/main.cpp
[100%] [32m[1mLinking CXX executable testexe[0m
/usr/local/Cellar/cmake/3.7.2/bin/cmake -E cmake_link_script CMakeFiles/testexe.dir/link.txt --verbose=1
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++    -Wl,-search_paths_first -Wl,-headerpad_max_install_names  CMakeFiles/testexe.dir/main.o  -o testexe  
Undefined symbols for architecture x86_64:
  "Catch::LeakDetector::LeakDetector()", referenced from:
      ___cxx_global_var_init in main.o
  "Catch::Session::run(int, char**)", referenced from:
      _main in main.o
  "Catch::Session::Session()", referenced from:
      _main in main.o
  "Catch::Session::~Session()", referenced from:
      _main in main.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [testexe] Error 1
make[1]: *** [CMakeFiles/testexe.dir/all] Error 2
make: *** [all] Error 2
```

### Extra information

This repros against `HEAD` of the Catch2 repository on Mac OS X 10.10.5.

Using the single include (`Catch2/single_include/catch.hpp`) works just fine.

**Comment by rcook** [comment]
Apologies if this behaviour change is by design.

**Comment by horenmar** [comment]
If I understand you correctly, the error happens when clone the repository and include `include/catch.hpp`, correct?

Then that is mostly intended. With Catch 2, the development version of Catch uses actual `.cpp` files, that are later stitched into the single include. This means that if you aren't using the single include version of catch, you have to compile the `.cpp` files separately and then link against them separately.

**Comment by rcook** [comment]
That's right. It sounds like this behaviour change is by design then.

**Comment by horenmar** [comment]
@rcook I would call it an unintended side effect of internal changes, but since it made our development easier and using the single include version is the recommended way of consuming Catch, we intend to keep it.

Thanks for the report though.

**Comment by mattgodbolt** [comment]
Sorry to wake this: but if one wishes to use the reporters (like the TeamCity one), how is it best to consume the library? It seems the single-header version doesn't include the teamcity reporter, unless I'm missing something! Thanks:)

**Comment by horenmar** [comment]
@mattgodbolt Download the reporter header separately, include it from the implementation file. After that you should have binary that accepts new value to the `-r` argument.

**Comment by martinmoene** [comment]
Should it be possible to use the reporters with the single header file?

```
// Let Catch provide main():
#define CATCH_CONFIG_MAIN

#include "catch.hpp"

#ifdef   CATCH_EXAMPLE_RPT_1
#include CATCH_EXAMPLE_RPT_1
#endif
```

Doing the following (pardon the funny %% of my Windows 'shell'):
```
prompt>g++ -std=c++11 -Wall -I%CATCH_SINGLE_INCLUDE% -I%CATCH_SINGLE_INCLUDE%/../include/ -DCATCH_EXAMPLE_RPT_1=\"reporters/catch_reporter_teamcity.hpp\" -c 200-Rpt-CatchMain.cpp
prompt>g++ -std=c++11 -Wall -I%CATCH_SINGLE_INCLUDE% -o 207-Rpt-TeamCityReporter 207-Rpt-TeamCityReporter.cpp 200-Rpt-CatchMain.o && 207-Rpt-TeamCityReporter --success
```
Yields errors in the first step:
```
In file included from ../single_include/../include/reporters/catch_reporter_teamcity.hpp:17:0,
                 from 200-Rpt-CatchMain.cpp:12:
../single_include/../include/reporters/../internal/catch_enforce.h:16:0: warning: "CATCH_PREPARE_EXCEPTION" redefined
 #define CATCH_PREPARE_EXCEPTION( type, msg ) \

In file included from 200-Rpt-CatchMain.cpp:9:0:
../single_include/catch.hpp:1828:0: note: this is the location of the previous definition
 #define CATCH_PREPARE_EXCEPTION( type, msg ) \

In file included from ../single_include/../include/reporters/../internal/catch_enforce.h:10:0,
                 from ../single_include/../include/reporters/catch_reporter_teamcity.hpp:17,
                 from 200-Rpt-CatchMain.cpp:12:
../single_include/../include/reporters/../internal/catch_common.h:27:12: error: redefinition of 'struct Catch::CaseSensitive'
     struct CaseSensitive { enum Choice {
. . .
```

**Comment by horenmar** [comment]
@philsquared PHIIIIIIIIL!!

This got broken in 56e10756. I am going to fix it tomorrow.

**Comment by martinmoene** [comment]
Thanks!

**Comment by horenmar** [comment]
It should work with ToT now, but there are some open questions to solve...

Specifically, reporters are made to work with, and are tested against, current include files rather than the last released single header version. We should probably start copying reporters to `single_include` on release, so that it is easy to get assuredly compatible versions.

**Comment by philsquared** [comment]
Yeah, I was talking with @mattgodbolt just yesterday about that - although more from the perspective that we should include them alongside the release files in the release area.

While I agree they should probably go in `single_include`, it does contradict the naming a little. I'm not sure the best approach there (although it takes me back to an old proposal I had of having the "dev" sources in a separate repo/ branch, and then having a "release" repo/ branch that has only the things needed. Unfortunately there were things about that that don't work out too cleanly either).

**Comment by martinmoene** [comment]
Once reporter examples appear, their compilation also provides some feedback.

mmm, what is ToT?

**Comment by horenmar** [comment]
@martinmoene Top of Trunk/ HEAD at master.

**Comment by martinmoene** [comment]
It improved:
```
prompt>g++ -std=c++11 -Wall -I%CATCH_ROOT% -DCATCH_EXAMPLE_RPT_1=\"include/reporters/catch_reporter_teamcity.hpp\" -c 200-Rpt-CatchMain.cpp
In file included from 200-Rpt-CatchMain.cpp:12:0:
../include/reporters/catch_reporter_teamcity.hpp: In member function 'virtual bool Catch::TeamCityReporter::assertionEnded(const Catch::AssertionStats&)':
../include/reporters/catch_reporter_teamcity.hpp:72:17: error: 'ReusableStringStream' was not declared in this scope
                 ReusableStringStream msg;
                 ^~~~~~~~~~~~~~~~~~~~
../include/reporters/catch_reporter_teamcity.hpp:72:17: note: suggested alternative: 'MessageStream'
                 ReusableStringStream msg;
                 ^~~~~~~~~~~~~~~~~~~~
                 MessageStream
../include/reporters/catch_reporter_teamcity.hpp:74:41: error: 'msg' was not declared in this scope
                     printSectionHeader( msg.get() );
                                         ^~~
../include/reporters/catch_reporter_teamcity.hpp:77:17: error: 'msg' was not declared in this scope
                 msg << result.getSourceInfo() << "\n";
                 ^~~
```

**Comment by horenmar** [comment]
Thats the "reporters expect current state instead of last release" part :smile:. Try it against regenerated single header.

**Comment by martinmoene** [comment]
Argh, that helps:

```
g++ -std=c++11 -Wall -I$(CATCH_ROOT) -DCATCH_EXAMPLE_RPT_1="include/reporters/catch_reporter_teamcity.hpp" -c 200-Rpt-CatchMain.cpp
g++ -std=c++11 -Wall -I$(CATCH_ROOT) -o 207-Rpt-TeamCityReporter 207-Rpt-TeamCityReporter.cpp 200-Rpt-CatchMain.o && 207-Rpt-TeamCityReporter --list-reporters
Available reporters:
  compact:   Reports test results on a single line, suitable for IDEs
  console:   Reports test results as plain lines of text
  junit:     Reports test results in an XML format that looks like Ant's
               junitreport target
  teamcity:  Reports test results as TeamCity service messages
  xml:       Reports test results as an XML document
```

Thanks!
