### ISSUE TITLE
List of platforms/compilers known to work?

### ISSUE THREAD

**Issue by martinmoene** [catchorg/Catch2#103]
I couldn't find this information in explicit form in Wiki or files.

**Comment by DavidEGrayson** [comment]
I have been using the latest tagged version of catch on gcc version 4.9.2 from the MSYS2 project.  They provide both a 32-bit version and a 64-bit version and I have been using catch on both.  They both work fine, except for the minor issue I am about to report...

**Comment by DavidEGrayson** [comment]
Sorry, I just discovered a major bug with the 32-bit MSYS2 mingw-w64 compiler when I updated from catch 1.1 to 1.2.1, so I have deleted my comment in order to not lead others astray.  I will try to get a bug report to you soon.

**Comment by DavidEGrayson** [comment]
Catch works for me on gcc 4.9.2 (mingw-w64) provided by the [MSYS2](https://msys2.github.io/) project.  I have used both the 32-bit and 64-bit versions of their mingw-w64 compiler and it works fine.  I have not run the Catch test suite though.

(For a while there, I thought there was a serious bug because I updated from version of 1.1 to 1.2.1 without recompiling all of the binaries in my test suite.  That caused every CHECK to fail if the value was true and succeed if the value was false, which is the opposite of correct.  Sorry if you saw some of my earlier messages that I deleted.)

**Comment by rollbear** [comment]
For Linux you can also add gcc 4.9 and 5.1, plus clang 3.6.

**Comment by patrickmmartin** [comment]
You can also add 
IBM XLC on AIX (POWER BE) - XL 11.1.0
Solaris (SPARC BE)  SunPro 5.12.0

**Comment by BrendanSimon** [comment]
I've had success with Catch using Embarcadero (was Borland) C++ Builder XE7, but only using the the 64-bit version of the compiler, which is based on clang (v3.1+SVN).

The 32-bit compiler is proprietary and claims to be C++98 compliant, but Catch will not compile.

Note: the newer versions of Embarcadero (10.2 Tokyo, and possibly 10.1 Berlin?) have migrated to clang based 32-bit compilers (and 64-bit of course), so I presume they would work.  These are based on clang v3.3 so **should** be C++11 compliant.

**Comment by BrendanSimon** [comment]
I've just tried using the **IAR EWARM (v7.8.4)** compiler to run on an ARM embedded system, and it fails to build.

I had to add `#include <stddef.h>` as `size_t` was undefined.  An easy fix, but why?

Major problem is `stack_t` does not exist in any header files.

**How important is `stack_t` and can be be stubbed out somehow to get Catch working?**

**Comment by horenmar** [comment]
@brendansimon on most platforms including the C++ version of C headers also puts the names into global namespace, which we apparently rely on somewhere.

As to your second question, `stack_t` is a type related to POSIX signal handling. You can bypass it by defining `CATCH_CONFIG_NO_POSIX_SIGNALS`.

**Comment by horenmar** [comment]
Note also that if the compiler provides sufficiently unique macro to identify itself, you can open a PR and add detection so that POSIX signals are disabled automatically, see [catch_compiler_capabilities.h](https://github.com/philsquared/Catch/blob/master/include/internal/catch_compiler_capabilities.h#L84)

**Comment by BrendanSimon** [comment]
I have Catch working on **IAR EWARM (v7.8)**

I modified the **single header version (v1.10.0)** for now (if `__IAR_SYSTEMS_ICC__` is defined)

* `#define CATCH_INTERNAL_CONFIG_NO_POSIX_SIGNALS`
* `#define CATCH_CONFIG_COLOUR_NONE`
* `#include <stddef.h>    // for size_t`
* `#include <c/time.h>    // for sprintf`
* `#include <c/time.h>    // for time_t`
* `UInt64 getCurrentTicks() { return 0; }    // FIXME: later !!`
* change `it->front()` to `*it->begin()`
* implement my own `main()` (as per the docs)
* increased IAR stack size from `0x400` to `0x1000`
* increased IAR heap size from `0x200` to `0x4000` (generally don't use malloc)

I will look at implementing this properly in the repo and open a PR :)

**Are there any configurations to reduce memory usage ??**

**Comment by horenmar** [comment]
@BrendanSimon There isn't any, no. Catch is primarily aimed at platforms with enough memory/CPU that its tendency to allocate and throw `std::string`s around isn't a problem. There is some effort to support free standing applications (ie it allows redefinition of output streams), but memory is seen as expendable.

**Comment by philippeVerney** [comment]
In order to help to centralize information
- VS2013 (and prior versions) is not supported with Catch2 (#1123 )

**Comment by Mike4Online** [comment]
I get a ton of compile errors trying to build a project that uses the all-in-one header from Catch2 version 2.12.2, building on Debian 7 (Wheezy) 64-bit with GCC (g++) 4.7.2:

```
/usr/bin/c++  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE_SOURCE64 -D_THREAD_SAFE -I/source/Linux/unittest-catch2 -g  -O0 -g3 -fPIE -pthread -fpermissive -march=x86-64 -Wall -Wextra -std=gnu++11 -o CMakeFiles/unittest-catch2.dir/source/AllPlatforms/CollectorUtils/unittest-Catch2/main.cpp.o -c /source/AllPlatforms/CollectorUtils/unittest-Catch2/main.cpp

In file included from main.cpp:2:0:
/catch2/catch.hpp:3880:5: error: expected unqualified-id before ‘[’ token
/catch2/catch.hpp:3889:5: error: expected unqualified-id before ‘[’ token
/catch2/catch.hpp:3891:5: error: expected unqualified-id before ‘[’ token
/catch2/catch.hpp:3893:5: error: expected unqualified-id before ‘[’ token
In file included from main.cpp:2:0:
catch.hpp: In constructor ‘Catch::Generators::FilterGenerator<T, Predicate>::FilterGenerator(P&&, Catch::Generators::GeneratorWrapper<T>&&)’:
catch.hpp:4168:21: error: ‘throw_exception’ is not a member of ‘Catch’
catch.hpp: In constructor ‘Catch::Generators::ChunkGenerator<T>::ChunkGenerator(size_t, Catch::Generators::GeneratorWrapper<T>)’:
catch.hpp:4304:25: error: ‘throw_exception’ is not a member of ‘Catch’
catch.hpp: At global scope:
catch.hpp:4455:17: error: expected identifier before ‘alignof’
catch.hpp:4455:17: error: expected ‘,’ or ‘...’ before ‘alignof’
catch.hpp:4455:27: error: expected ‘;’ at end of member declaration
catch.hpp: In constructor ‘Catch::Generators::IteratorGenerator<T>::IteratorGenerator(InputIterator, InputSentinel)’:
catch.hpp:4715:13: error: ‘throw_exception’ is not a member of ‘Catch’

```
The above list is partial.  The project includes only a main.cpp - no actual test classes.  Changing -std from gnu++11 to c++11 does not help.

Any ideas?

**Comment by pmcgee69** [comment]
I've compiled Catch2 using Embarcadero C++ Builder 10.3.3 Community Edition, but (also) only using the the 64-bit version of the compiler, which is based on clang (5.0.0).  Requires #define CATCH_CONFIG_NO_GLOBAL_NEXTAFTER .  32 bit clang currently no go.

**Comment by robinmoussu** [comment]
> Good idea. I've started this wiki page: https://github.com/philsquared/Catch/wiki/What-compilers-does-CATCH-work-with

The link provided doesn’t exist anymore. And given that this thread is very old, is Catch2 version 3 still compatible with the old compilers like gcc4.9 and clang3.6? I cannot find in the documentation what is the minimum version of c++ supported (is it 11, 14 or 17?).

**Comment by dimztimz** [comment]
> The link provided doesn’t exist anymore. And given that this thread is very old, is Catch2 version 3 still compatible with the old compilers like gcc4.9 and clang3.6? I cannot find in the documentation what is the minimum version of c++ supported (is it 11, 14 or 17?).

Catch2 v3 requires C++14 which means it needs at least GCC 5.
