### ISSUE TITLE
Fail to compile on macOS 10.14.6 with certain header

### ISSUE THREAD

**Issue by zhuanhao-wu** [catchorg/Catch2#1789]
**Describe the bug**
When there is a header called `Signal.h` specified in `-I` option, catch2 may not find the correct `signal.h`.

**Expected behavior**
Catch2 should identify `signal.h` correctly.

**Reproduction steps**

With the following setup:
```
./inc
./inc/Signal.h
./catch.hpp
./main.cpp
```
where `Signal.h` is an empty file and `main.cpp` includes the following:
```
#define CATCH_CONFIG_MAIN
#include "catch.hpp"
```

Then compiling `main.cpp` gives (g++ here is an alias of clang):
```
$ g++ -o main.cpp.o main.cpp  -std=c++11 -I ./inc/
In file included from main.cpp:2:
./catch.hpp:10696:9: error: use of undeclared identifier 'raise'
        raise( sig );
        ^
./catch.hpp:10705:9: error: use of undeclared identifier 'sigaltstack'
        sigaltstack(&sigStack, &oldSigStack);
        ^
./catch.hpp:10711:13: error: no matching constructor for initialization of 'sigaction'
            sigaction(signalDefs[i].id, &sa, &oldSigActions[i]);
            ^         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/sys/signal.h:286:9: note: candidate constructor (the implicit copy constructor) not viable: requires 1 argument, but 3 were provided
struct  sigaction {
        ^
/usr/include/sys/signal.h:286:9: note: candidate constructor (the implicit move constructor) not viable: requires 1 argument, but 3 were provided
/usr/include/sys/signal.h:286:9: note: candidate constructor (the implicit default constructor) not viable: requires 0 arguments, but 3 were provided
In file included from main.cpp:2:
./catch.hpp:10723:17: error: no matching constructor for initialization of 'sigaction'
                sigaction(signalDefs[i].id, &oldSigActions[i], nullptr);
                ^         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/sys/signal.h:286:9: note: candidate constructor (the implicit copy constructor) not viable: requires 1 argument, but 3 were provided
struct  sigaction {
        ^
/usr/include/sys/signal.h:286:9: note: candidate constructor (the implicit move constructor) not viable: requires 1 argument, but 3 were provided
/usr/include/sys/signal.h:286:9: note: candidate constructor (the implicit default constructor) not viable: requires 0 arguments, but 3 were provided
In file included from main.cpp:2:
./catch.hpp:10726:13: error: use of undeclared identifier 'sigaltstack'
            sigaltstack(&oldSigStack, nullptr);
            ^
5 errors generated.
```

**Platform information:**

 - OS: **macOS 10.14.6**
 - Compiler+version: **Apple LLVM version 10.0.1 (clang-1001.0.46.4)**
 - Catch version: **v2.10.2**

**Additional context**

**Comment by horenmar** [comment]
What you are asking for is literally impossible. You tell the compiler that there are more possible include paths, so it looks there a finds a file that looks good enough (`Signal.h`) and then everything breaks.

Because OS X's FS is case-preserving but case-insensitive, there is no difference between `signal.h` and `Signal.h` as far as the file system (and thus the compiler) is concerned.

**Comment by zhuanhao-wu** [comment]
Just to comment on my workaround for future references.

When using `clang`, there is an `-iquote` option which specifies a directory that can only be searched in the form `#include "xxx.h"` and not `#incldue <xxx.h>`. And limit the code to use `#include "Signal.h"` and `#incldue <signal.h>`

Thanks
